#!/usr/bin/env node

/**
 * Post-build script: generates static HTML from wiki/ and blog/ markdown.
 * Run after `vite build` — output goes to dist/wiki/ and dist/blog/.
 *
 * Generated by Epicraft.
 */

import fs from "fs";
import path from "path";
import { marked } from "marked";
import matter from "gray-matter";

const WIKI_DIR = "wiki";
const BLOG_DIR = "blog";
const DIST_DIR = "dist";

// -- HTML Template ------------------------------------------------------------

function htmlTemplate(title, body, meta) {
  const metaBar = meta
    ? `<div class="meta">
        ${meta.date ? `<time>${meta.date}</time>` : ""}
        ${meta.ticket ? `<span>Ticket: ${meta.ticket}</span>` : ""}
        ${meta.status === "draft" ? `<span class="draft">Draft</span>` : ""}
      </div>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { margin: 0; padding: 0; }
    .article {
      max-width: 48rem;
      margin: 2rem auto;
      padding: 0 1.5rem;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      line-height: 1.7;
      color: #1a1a1a;
    }
    h1 { font-size: 2rem; font-weight: 700; margin: 2rem 0 1rem; border-bottom: 1px solid #e5e5e5; padding-bottom: 0.5rem; }
    h2 { font-size: 1.5rem; font-weight: 600; margin: 1.75rem 0 0.75rem; }
    h3 { font-size: 1.25rem; font-weight: 600; margin: 1.5rem 0 0.5rem; }
    p { margin: 0.75rem 0; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    code { background: #f3f4f6; padding: 0.15rem 0.35rem; border-radius: 0.25rem; font-size: 0.875em; }
    pre { background: #f3f4f6; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; margin: 1rem 0; }
    pre code { background: none; padding: 0; }
    ul, ol { padding-left: 1.5rem; margin: 0.75rem 0; }
    li { margin: 0.25rem 0; }
    blockquote { border-left: 3px solid #d1d5db; padding-left: 1rem; margin: 1rem 0; color: #6b7280; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { border: 1px solid #e5e5e5; padding: 0.5rem 0.75rem; text-align: left; }
    th { background: #f9fafb; font-weight: 600; }
    .meta { display: flex; gap: 1rem; font-size: 0.875rem; color: #6b7280; margin-bottom: 1.5rem; padding-bottom: 0.75rem; border-bottom: 1px solid #e5e5e5; }
    .draft { background: #fef3c7; color: #92400e; padding: 0.1rem 0.5rem; border-radius: 0.25rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
    .nav-list { list-style: none; padding: 0; }
    .nav-list li { margin: 0.5rem 0; }
    .nav-list a { font-size: 1.05rem; }
    .post-date { color: #6b7280; font-size: 0.875rem; margin-left: 0.5rem; }
  </style>
</head>
<body>
  <article class="article">
    ${metaBar}
    ${body}
  </article>
</body>
</html>`;
}

// -- Wiki Builder -------------------------------------------------------------

function buildWiki() {
  const wikiDir = path.resolve(WIKI_DIR);
  if (!fs.existsSync(wikiDir)) return;

  const outDir = path.join(DIST_DIR, "wiki");
  const sections = [];
  let indexHtml = "";

  function walk(dir, prefix) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name), path.join(prefix, entry.name));
      } else if (entry.name.endsWith(".md")) {
        const mdContent = fs.readFileSync(path.join(dir, entry.name), "utf-8");
        const htmlBody = marked.parse(mdContent);

        // Determine output filename
        let outName;
        if (entry.name === "index.md" && prefix === "") {
          outName = "index.html";
        } else if (entry.name === "README.md") {
          outName = "index.html";
        } else {
          outName = entry.name.replace(/\.md$/, ".html");
        }

        // Rewrite .md links to .html for wiki cross-links
        // Resolve relative paths against current directory (prefix)
        const rewrittenBody = htmlBody.replace(
          /href="([^"]*)\.md"/g,
          (match, p1) => {
            const resolved = prefix ? path.join(prefix, p1) : p1;
            if (p1.endsWith("/README") || p1 === "README") {
              return `href="/wiki/${resolved.replace(/\/?README$/, "/")}"`;
            }
            return `href="/wiki/${resolved}.html"`;
          },
        );

        const outPath = path.join(outDir, prefix, outName);
        fs.mkdirSync(path.dirname(outPath), { recursive: true });

        const title = mdContent.match(/^#\s+(.+)$/m)?.[1] || entry.name;
        fs.writeFileSync(outPath, htmlTemplate(title, rewrittenBody, null));

        // Track content for the combined home page
        const isRootIndex = entry.name === "index.md" && prefix === "";
        if (isRootIndex) {
          indexHtml = rewrittenBody;
        } else if (entry.name !== "README.md") {
          const sortKey = prefix ? prefix + "/" + entry.name : entry.name;
          sections.push({ sortKey, html: rewrittenBody });
        }
      }
    }
  }

  walk(wikiDir, "");

  // Rebuild index.html as a combined page — intro at top, all content inlined
  if (sections.length > 0) {
    sections.sort((a, b) => a.sortKey.localeCompare(b.sortKey));
    const combined = indexHtml + sections.map((s) => "<hr>" + s.html).join("");
    fs.writeFileSync(
      path.join(outDir, "index.html"),
      htmlTemplate("Project Wiki", combined, null),
    );
  }

  console.log("[build-wiki] Wiki pages generated in dist/wiki/");
}

// -- Blog Builder -------------------------------------------------------------

function buildBlog() {
  const blogDir = path.resolve(BLOG_DIR);
  if (!fs.existsSync(blogDir)) return;

  const outDir = path.join(DIST_DIR, "blog");
  fs.mkdirSync(outDir, { recursive: true });

  const posts = [];

  for (const filename of fs.readdirSync(blogDir)) {
    if (!filename.endsWith(".md") || filename === "README.md") continue;

    const raw = fs.readFileSync(path.join(blogDir, filename), "utf-8");
    const { data, content } = matter(raw);

    const htmlBody = marked.parse(content);
    const slug = filename.replace(/\.md$/, "");
    const title = data.title || slug;
    const date = data.date ? String(data.date) : "";
    const ticket = data.ticket ? String(data.ticket) : "";
    const status = data.status || "published";

    const meta = { date, ticket, status };

    const outPath = path.join(outDir, slug + ".html");
    fs.writeFileSync(outPath, htmlTemplate(title, htmlBody, meta));

    posts.push({ slug, title, date, status, html: htmlBody, meta });
  }

  // Build blog index page — listing at top, full content inlined below
  posts.sort((a, b) => b.date.localeCompare(a.date));

  let indexBody;
  if (posts.length === 0) {
    indexBody = "<h1>Project Blog</h1><p>No blog posts yet. Posts are auto-drafted by Epicraft after each PR.</p>";
  } else {
    const listing = `<h1>Project Blog</h1>
      <ul class="nav-list">
        ${posts.map((p) => `<li><a href="/blog/${p.slug}.html">${p.title}</a><span class="post-date">${p.date}</span></li>`).join("\n        ")}
      </ul>`;
    const fullPosts = posts.map((p) => {
      const metaBar = `<div class="meta">
        ${p.meta.date ? `<time>${p.meta.date}</time>` : ""}
        ${p.meta.ticket ? `<span>Ticket: ${p.meta.ticket}</span>` : ""}
        ${p.meta.status === "draft" ? `<span class="draft">Draft</span>` : ""}
      </div>`;
      return `<hr>${metaBar}<h2>${p.title}</h2>${p.html}`;
    }).join("");
    indexBody = listing + fullPosts;
  }

  fs.writeFileSync(
    path.join(outDir, "index.html"),
    htmlTemplate("Project Blog", indexBody, null),
  );

  console.log(`[build-wiki] Blog index + ${posts.length} posts generated in dist/blog/`);
}

// -- Nav Injection ------------------------------------------------------------

function injectNav() {
  const indexPath = path.join(DIST_DIR, "index.html");
  if (!fs.existsSync(indexPath)) return;

  let html = fs.readFileSync(indexPath, "utf-8");
  if (html.includes("epicraft-wiki-nav")) return;

  const nav = [
    '<style>#epicraft-wiki-nav{position:fixed;top:1rem;right:1.5rem;z-index:9999;display:flex;gap:1rem;font-family:-apple-system,BlinkMacSystemFont,sans-serif;font-size:0.8rem}',
    '#epicraft-wiki-nav a{color:rgba(255,255,255,0.45);text-decoration:none;transition:color 0.15s}',
    '#epicraft-wiki-nav a:hover{color:rgba(255,255,255,0.85)}</style>',
    '<nav id="epicraft-wiki-nav"><a href="/wiki">Wiki</a><a href="/blog">Blog</a></nav>',
  ].join("");

  html = html.replace("</body>", nav + "\n</body>");
  fs.writeFileSync(indexPath, html);
  console.log("[build-wiki] Wiki/blog nav injected into index.html");
}

// -- Main ---------------------------------------------------------------------

buildWiki();
buildBlog();
injectNav();
